### ISSUE TITLE
リリース用のGitHub Actionsを追加する

### ISSUE THREAD

**Issue by XeicuLy** [XeicuLy/eslint-plugin-xeiculy#5]
- build
- npm publish
- リリースノート作成

を行うワークフローを追加する

**Comment by XeicuLy** [comment]
```
name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'バージョンタイプ (patch | minor | major)'
        required: false
        default: 'auto'
        type: choice
        options:
          - auto
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Build
        run: pnpm build
      
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      
      - name: Release
        if: ${{ inputs.version == 'auto' }}
        run: pnpm release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Release with specific version
        if: ${{ inputs.version != 'auto' }}
        run: changelogen --release --push --publish --${{ inputs.version }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
